### PR TITLE
CoffeeInn - Vilnius

### PR DESCRIPTION
**Pull request by e-stankevicius**
There are more, but people will use homepage for that, tought.

### CODE REVIEW

**Comment by kaaes** [comment]
wow, another country :) nice! thanks :)

**Comment by nazgob** [comment]
@kaaes you're merging like crazy :)

**Comment by e-stankevicius** [comment]
I see lots of cities came in.

**Comment by nazgob** [comment]
yup! stay tuned for redesign that will better adapt multiple countries/cities

**Comment by e-stankevicius** [comment]
Sooo... Maybe afteral you gana make dinamic list. Or webpage where everybody can add coffe shop.

**Comment by nazgob** [comment]
it will stay pull-request only for now, just to be sure we have geeks contributing :)

**Pull request merged**
